### ISSUE TITLE
Disabled effects names still appear on items when enchanting

### ISSUE THREAD

**Issue by SmallSansSerif** [zizmax/AcuteLoot#13]
With effects disabled both all effects or individuals set false you still get the disabled names appearing on items. 

Can this be fixed? 

Setting the percentage to 0 and re-testing FYI.

**Comment by zizmax** [comment]
Hey @SmallSansSerif, thanks for reporting this. Did you retry with setting percentage to 0? I think that is likely the issue.

The enabling/disabling is for the effects to execute, and the chances are for the loot generator. I will make it more clear in the next update to the config/plugin.

**Comment by SmallSansSerif** [comment]
Yup, that worked. Thanks for your response. Very cool plugin.

**Comment by zizmax** [comment]
Thank you! I'd really appreciate a review on the Spigot page! :)
