### ISSUE TITLE
2 Request: Randomized Items drops with custom enchants and without & MythicMobs Support

### ISSUE THREAD

**Issue by AlternativeSoap** [zizmax/AcuteLoot#29]
From Spigot: Could you make it so all mobs will drop randomized items with and without enchantments.
Also add so MythicMobs can drop it. 

More detailed meaning:

Add that all MythicMobs can drop it. I've got a MythicMobs file that change every vanilla mob to mythicmob with levels but still vanilla and added some extra mobs.
Also add that custom mobs can drop it. Maybe a section in config where we just write MythicMobs names.
https://www.spigotmc.org/resources/phatloots-loot-tables-conditions-block-loots-mob-drops-1-13-1-16.68925/
Phatloots does that but doesn't work with MythicMobs when dropping random items with and without enchantments. It's oudated.

Also maybe add support for EcoEnchants so some items will drop items with enchantments with a chance or with that system "common,uncommon,legendary"
https://www.spigotmc.org/resources/%E2%9A%A1-1-16-1-17-ecoenchants-%E2%9C%A8-230-custom-enchantments-%E2%9C%85-essentials-cmi-support.79573/

I hope this give you something to work with. :)

**Comment by zizmax** [comment]
Great feature suggestion! The first iteration of this feature will only be for all mobs/vanilla mobs. Having a specific compatibility with MythicMobs may require working directly with the MM API. Getting familiar with the API and learning how to work with it may take some time.

**Comment by AlternativeSoap** [comment]
Will this ever happen?

**Comment by zizmax** [comment]
@AlternativeSoap Mob drops are supported in the latest update!

**Comment by AlternativeSoap** [comment]
Seems for me it doesn't work?

**Comment by AlternativeSoap** [comment]
Got no mobs dropping Acuteloot

**Comment by AlternativeSoap** [comment]
My bad! I needed to reset my files.
Thanks for this! Keep it up. ;)
