### ISSUE TITLE
Suggestion about compatibility / Issue

### ISSUE THREAD

**Issue by AlternativeSoap** [zizmax/AcuteLoot#32]
Could you add compatibility to this plugin. When Terra is generating structures Acuteloot doesn't spawn loot inside the chest if it's possible

https://www.spigotmc.org/resources/terraformgenerator-alpha.75132/

Also I think it could be great for many. Free Terra World Generationg plugin with free random item generating stuff plugin. That's great!

**Comment by zizmax** [comment]
This is a great idea, and something I want to do with OhTheDungeonsYou'llGo as well, but honestly I'm not sure how to accomplish it. It's tough to distinguish a "natural" chest from a chest placed by a player. 

What we'd need to make this work is some sort of signal that a particular chest was placed by a world-gen plugin. Maybe some sort of metadata, or a specific item or something. That way, AcuteLoot could overwrite the chest when it detects that signal. 

Do you know if there's a way in TerraformGenerator to do something like that?
