### ISSUE TITLE
Manmade chests fill with loot

### ISSUE THREAD

**Issue by Gbird884** [zizmax/AcuteLoot#34]
I placed chests down and when I opened them they had filled with loot

**Comment by zizmax** [comment]
Hey @Gbird884, thanks for reporting your issue. We're going to need more information in order to understand what may be going on. Would you be able to share a screen recording of the issue?

**Comment by Gbird21** [comment]
It's fine I fixed it by literally reinstalling the plugin. Thanks anyway.
