### ISSUE TITLE
Getting a error with loot-category-lore

### ISSUE THREAD

**Issue by Ibesh** [zizmax/AcuteLoot#39]
In the config, I tried to turn off the function `loot-category-lore:` by changing `enabled: true` to `enabled: false`. This is gave me a internal error when I did `/al new`. I got the following error in the console: https://hatebin.com/qqejbobovl. 

I've also got a quick question. Do RGB/HEX colours work for the `rarities:` section in the config? I'd like to use some different colours then the standard mc ones 😅 

p.s. the links to the discord server do not work (on both spigot and github).

**Comment by zizmax** [comment]
Thank you for the bug report!

The latest version (2.11.2) should fix the issue!

Could you please create a separate issue for the RGB colours? I'll look into it.

Also, attempting to fix the Discord link as well.

**Comment by zizmax** [comment]
Discord link should be fixed! Let me know if you still have issues

**Comment by Ibesh** [comment]
Hi! 
The discord link works and thank you for the quick bug fix! I've also found out that RGB works already (`&x&R&R&G&G&B&B`) 😄. 

Thanks a lot for your help. If I have any other questions or I bump in to a bug, I'll let you know on here or discord 😃

**Comment by zizmax** [comment]
You're welcome! We'd greatly appreciate a review on Spigot! https://www.spigotmc.org/resources/acuteloot.81899/
