### ISSUE TITLE
1.19 support/lag

### ISSUE THREAD

**Issue by Folas1337** [zizmax/AcuteLoot#40]
I know the plugin doesn't officially support 1.19 yet but I got this huge lag spike while people were exploring the world with this plugin enabled:
https://timings.aikar.co/?id=4939eaa2c17a45e585875b221459a2cd

Maybe something you wanna look into :)

(cross posted from spigot as I know some developers aren't active on spigot as much)

**Comment by zizmax** [comment]
I'm looking into this a bit and can't find a clearly identifiable cause. Have you seen it happen any other time? Any idea how to reproduce it?

**Comment by Folas1337** [comment]
> I'm looking into this a bit and can't find a clearly identifiable cause. Have you seen it happen any other time? Any idea how to reproduce it?

Yes, it still keeps happening, even when just generating chunks, don't even have to open any chests or anything. Sometimes it happens when a chunk is generated, other times when the chunk is generated. I've never experienced this on 1.18 but it started happening in 1.19 quite randomly. I'll try and get you another timings when I get the chance to gather one.

**Comment by Folas1337** [comment]
Here's another one of those lag timings: https://timings.aikar.co/?id=93f3f7eaaef14137819e0b26190bf4c6

Mostly caused by this event it seems:
AcuteLoot::Task: acute.loot.LootCreationEventListener$1

**Comment by Folas1337** [comment]
Aha, after a lot of testing and asking people I finally got it fixed!
It must've been treasure maps that were causing it that were generated when chunks got loaded and sometimes when chests were opened, which probably caused AcuteLoot's tick to take just as long or something like that.

Either way, it's not happening anymore and I'm closing this ticket :)
_I'd love to see #41 to get looked into 😛_

**Comment by Folas1337** [comment]
Yeah, paper has a config option that allows you to turn them off entirely.
In the ./config/paper-world-defaults.yml
```yaml
environment:
  treasure-maps:
    enabled: false
```
That was what I've set it to :)
