### ISSUE TITLE
[Bug] Salvage GUI confirmation has to be clicked twice

### ISSUE THREAD

**Issue by StevenW-1** [zizmax/AcuteLoot#9]
You have to click the "confirm" button twice for it to 
change the status ready for a new acuteloot item

In this video I pressed the Confirm button twice
**Video 1** [gyazo.com - video](https://gyazo.com/f9d7eda3a57febb28690940dfaaad2d4)

**Why this is a problem:**
Because if a player does not press the Confirm button twice 
they will be stuck trying to salvage another item after

(In this video i was spamming the hopper button at the end, 
and the chat had the output: "Already salvaged")
**Video 2** [gyazo.com - video](https://gyazo.com/a4e3e1346fe70a081c4b7a6a923a7b35)

Plugin version: 2.0.2
Spigot version: Paperspigot 1.16.4
Errors: N/A

**Comment by zizmax** [comment]
Fixed in 2.0.3

**Comment by zizmax** [comment]
Fixed in 2.0.3
